package com.example.practice.user.service

import com.example.practice.user.model.User
import com.example.practice.user.model.UserSummary
import com.example.practice.user.model.CreateUserInput
import com.example.practice.user.model.UpdateUserInput
import com.example.practice.user.repository.UserRepository
import com.example.practice.user.validation.UserValidationService

import org.springframework.stereotype.Service
import reactor.core.publisher.Flux
import reactor.core.publisher.Mono
import java.time.Instant

@Service
class UserService(
    private val userRepository: UserRepository,
    private val userValidationService: UserValidationService
) {
    // find all users
    fun findAllUsers(): Flux<User>
    {
        return userRepository.findAll()
            .switchIfEmpty(Flux.error(NoSuchElementException("find error - No users found")))
            .onErrorResume { ex -> Mono.error(ex) }
    }

    // find an user by id
    fun findUserById(id: String): Mono<User>
    {
        return userRepository.findById(id)
            .switchIfEmpty(Mono.error(NoSuchElementException("find error - User not found with id: $id")))
            .onErrorResume { ex -> Mono.error(ex) }
    }

    // find summaries of all users
    fun findAllUserSummaries(): Flux<UserSummary> {
        return userRepository.findAll()
            .map { user -> UserSummary(requireNotNull(user.id), user.name, user.email) }
            .switchIfEmpty(Flux.error(NoSuchElementException("find error - No users found")))
            .onErrorResume { ex -> Mono.error(ex) }
    }

    // find the summary of a user by id
    fun findUserSummaryById(id: String): Mono<UserSummary> {
        return userRepository.findById(id)
            .flatMap { user -> Mono.just(UserSummary(requireNotNull(user.id), user.name, user.email)) }
            .switchIfEmpty(Mono.error(NoSuchElementException("find error - User not found with id: $id")))
            .onErrorResume { ex -> Mono.error(ex) }
    }

    fun createUser(createUserInput: CreateUserInput): Mono<Boolean> {
        return userValidationService.validateUserForCreate(createUserInput)
            .flatMap { vr ->
                // Illegal argument exception for validation errors
                if (!vr.isValid) return@flatMap Mono.error(IllegalArgumentException(vr.errorMessage ?: "validation failed"))

                // Create new user object with input data and current timestamp
                // id will be generated by MongoDB (when saving)
                val user = User(
                    id = null,
                    name = createUserInput.name,
                    email = createUserInput.email,
                    password = createUserInput.password,
                    createdAt = Instant.now()
                )
                // Save the user data to db
                userRepository.save(user)
                    .then(Mono.just(true))
                    // any errors usually duplicate key errors)
                    .onErrorResume { ex -> Mono.error(ex) }
            }
    }

    fun updateUser(updateUserInput: UpdateUserInput): Mono<User> {
        // Validate input data, and check if at least one field to update is provided
        return userValidationService.validateUserForUpdate(updateUserInput)
            .flatMap { vr ->
                // Illegal argument exception for validation errors
                if (!vr.isValid) return@flatMap Mono.error(IllegalArgumentException(vr.errorMessage ?: "validation failed"))
                
                // Fetch existing user using input id
                userRepository.findById(updateUserInput.id).
                flatMap { existing ->
                    // Only update fields provided in input, keep others unchanged
                    val updated = existing.copy(
                        name = updateUserInput.name ?: existing.name,
                        email = updateUserInput.email ?: existing.email,
                        password = updateUserInput.password ?: existing.password
                    )
                    // If user found, save the updated user data to db
                    userRepository.save(updated)
                        // any errors during communication with db. usually duplicate key errors
                        .onErrorResume { ex -> Mono.error(ex) }
                }
                .switchIfEmpty(Mono.error(NoSuchElementException("update error - User not found with id: ${updateUserInput.id}")))
                .onErrorResume { ex -> Mono.error(ex) }
            }
    }

    fun deleteUser(id: String): Mono<Boolean> {
        return userRepository.deleteById(id)
            .then(Mono.just(true))
            .switchIfEmpty(Mono.error(NoSuchElementException("delete error - User not found with id: $id")))
            .onErrorResume { ex -> Mono.error(ex) }
    }
}